# command -Denv=DEV -Dapollo.cacheDir=/opt/data/learning-dir -Dapollo.cluster=DEFAULT
# apollo 配置中心管理服务配置
server:
  port: 63010

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.94.129:8848                 #注册中心nacos地址
        namespace: 72990e80-c137-4cdc-9b6a-33e3ead0957d  #dev环境的namespace配置
        group: ${dev.group}                              #指定组的名称
    gateway:       #网关配置
      routes:
        - id: content-service #服务标识，不允许出现重复
          uri: lb://content-service #nacos注册的服务名称，实现负载均衡
          predicates:
            - Path=/content/** #匹配方式
        - id: system-service #服务标识，不允许出现重复
          uri: lb://system-service #nacos注册的服务名称，实现负载均衡
          predicates:
            - Path=/system/** #匹配方式
        - id: media-service #服务标识，不允许出现重复
          uri: lb://media-service #nacos注册的服务名称，实现负载均衡
          predicates:
            - Path=/media/** #匹配方式
        - id: search-service #服务标识，不允许出现重复
          uri: lb://search-service #nacos注册的服务名称，实现负载均衡
          predicates:
            - Path=/search/** #匹配方式

#配置开发组的名称
dev:
  group: xc-group



#日志配置
logging:
  config: classpath:log4j2-dev.xml


# 开启 feign 的远程调用使用熔断
feign:
  compression:
    request:
      enabled: true                   # 配置请求GZIP压缩
      min-request-size: 2048          # 配置压缩数据大小的下限
      mime-types[0]: text/xml         # 配置压缩支持的MIME TYPE
      mime-types[1]: application/xml
      mime-types[2]: application/json
    response:
      enabled: true                   # 配置响应GZIP压缩



ribbon:
  MaxAutoRetries: 1                  #对当前实例的重试次数 default 0
  ConnectTimeout: 3000               #设置连接超时时间 default 2000
  OkToRetryOnAllOperations: false    #对所有操作请求都进行重试 default false
  ReadTimeout: 20000                 #设置读取超时时间 default 5000
  MaxAutoRetriesNextServer: 1        #切换实例的重试次数 default 1